name: Update Translation Files

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_DB_NAME: './test_db.sqlite'
      INVENTREE_DB_ENGINE: django.db.backends.sqlite3
      INVENTREE_DEBUG: info
      INVENTREE_MEDIA_ROOT: ./media
      INVENTREE_STATIC_ROOT: ./static
      INVENTREE_BACKUP_DIR: ./backup

    steps:
      - name: Checkout Code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
      - name: Set up Python 3.9
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # pin@v4.3.0
        with:
          python-version: 3.9
      - name: Set up Node 16
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b  # pin to v3.5.0
        with:
          node-version: 16
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          pip3 install invoke
          invoke install
      - name: Make Translations
        run: invoke translate
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b l10_local
          git add "*.po"
          git commit -m "updated translation base"
      - name: Push changes
        uses: ad-m/github-push-action@4dcce6dea3e3c8187237fc86b7dfdc93e5aaae58 # pin@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: l10
          force: true
